### ISSUE TITLE
Executar exemplo do datasus para integração PDQ

### ISSUE THREAD

**Issue by flaviociaware** [flaviociaware/cwEnsaiosWeb#1]
Utilizando a documentação abaixo executar o exemplo para consumir o serviço PDQ do datasus em ambiente de homologação:
http://datasus.saude.gov.br/interoperabilidade/catalogo-de-servicos

**Comment by flaviociaware** [comment]
A documentação foi seguida porém ocorre o erro 403 que é acesso negado.

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: com.sun.xml.internal.ws.wsdl.parser.InaccessibleWSDLException: 2 counts of InaccessibleWSDLException.

java.io.IOException: Got Server returned HTTP response code: 403 for URL: https://servicoshm.saude.gov.br/cadsus/PDQSupplier while opening stream from https://servicoshm.saude.gov.br/cadsus/PDQSupplier
java.io.IOException: Got Server returned HTTP response code: 403 for URL: https://servicoshm.saude.gov.br/cadsus/PDQSupplier?wsdl while opening stream from https://servicoshm.saude.gov.br/cadsus/PDQSupplier?wsdl

	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.tryWithMex(Unknown Source)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(Unknown Source)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(Unknown Source)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.parseWSDL(Unknown Source)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(Unknown Source)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(Unknown Source)
	at com.sun.xml.internal.ws.spi.ProviderImpl.createServiceDelegate(Unknown Source)
	at javax.xml.ws.Service.<init>(Unknown Source)
	at ihe.iti.pdqv3._2007.PDQSupplierService.<init>(PDQSupplierService.java:42)
	at br.com.ciaware.cadsus.PDQClientExample.<clinit>(PDQClientExample.java:98)


![image](https://cloud.githubusercontent.com/assets/7603518/11997587/b53e632e-aa66-11e5-9b83-e0e3af5bec86.png)

**Comment by joaoamilcar** [comment]
Boa tarde Flávio,

Compartilho da mesma barreira que você, a não ser que você já tenha resolvido.
Seguindo a especificação, gerei os códigos para o PDQSupplier e PIXManager.
A priori estou vendo as consultas com o PDQClientExample deles, mas já obtive retornos positivos. Estou usando as mesmas credenciais. Segue em anexo minhas telas. Alguma novidade por aí?

Tudo de bom!

![code](https://cloud.githubusercontent.com/assets/5265334/13296385/1a48714e-db0c-11e5-9b96-cbf20e014858.png)
![response](https://cloud.githubusercontent.com/assets/5265334/13296386/1a496ac2-db0c-11e5-91b0-27aa850b752a.png)

**Comment by flaviociaware** [comment]
Boa tarde João.

Não consegui evoluir, você conseguiu retornar alguma coisa?

[]´s

Em 24 de fevereiro de 2016 15:34, João Amílcar <notifications@github.com>
escreveu:

> Boa tarde Flávio,
>
> Compartilho da mesma barreira que você, a não ser que você já tenha
> resolvido.
> Seguindo a especificação, gerei os códigos para o PDQSupplier e PIXManager.
> A priori estou vendo as consultas com o PDQClientExample deles, mas já
> obtive retornos positivos. Estou usando as mesmas credenciais. Segue em
> anexo minhas telas. Alguma novidade por aí?
>
> Tudo de bom!
>
> [image: code]
> <https://cloud.githubusercontent.com/assets/5265334/13296385/1a48714e-db0c-11e5-9b96-cbf20e014858.png>
> [image: response]
> <https://cloud.githubusercontent.com/assets/5265334/13296386/1a496ac2-db0c-11e5-91b0-27aa850b752a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviociaware/cwEnsaiosWeb/issues/1#issuecomment-188397772>
> .
>



-- 
[]´s Dr. Flavio Barbosa
E-Mail: flavio@ciaware.com.br
Facebook: https://www.facebook.com/CIAware

**Comment by joaoamilcar** [comment]
Algumas pesquisas funcionaram, por exemplo:

//PesquisaOK (TesteRealizado)

Nome (SERGIO ARAUJO CORREIA LIMA),
CNS (703404696479515),
Sexo (UN)
Data de nascimento (19811110),
Nome da mãe (LINDYNALVA SOARES ARAUJO CORREIA LIMA) e;
CPF (66105234368).

O seu código (PDQClientExample) tem diferenças para o meu, mas não foi nenhuma alteração que eu fiz. Eles devem ter feito modificações nos contratos. Talvez se você repetir o processo do início seja um caminho.

**Comment by flaviociaware** [comment]
João, teria como compartilhar o seu fonte?

[]´s

Em 24 de fevereiro de 2016 17:47, João Amílcar <notifications@github.com>
escreveu:

> Algumas pesquisas funcionaram, por exemplo:
>
> //PesquisaOK (TesteRealizado)
>
> Nome (SERGIO ARAUJO CORREIA LIMA),
> CNS (703404696479515),
> Sexo (UN)
> Data de nascimento (19811110),
> Nome da mãe (LINDYNALVA SOARES ARAUJO CORREIA LIMA) e;
> CPF (66105234368).
>
> O seu código (PDQClientExample) tem diferenças para o meu, mas não foi
> nenhuma alteração que eu fiz. Eles devem ter feito modificações nos
> contratos. Talvez se você repetir o processo do início seja um caminho.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviociaware/cwEnsaiosWeb/issues/1#issuecomment-188447993>
> .
>



-- 
[]´s Dr. Flavio Barbosa
E-Mail: flavio@ciaware.com.br
Facebook: https://www.facebook.com/CIAware

**Comment by joaoamilcar** [comment]
https://github.com/joaoamilcar/barramento-cns

**Comment by vittorbraga** [comment]
Bom dia senhores, estou tentando consumir o webservice do data sus e tive o resultado igual ao do joaoamilcar, quando coloco um nome como parametro, que não seja SERGIO ARAUJO CORREIA LIMA, o retorno é vazio.

Vocês progrediram no desenvolvimento?

**Comment by AllanBorgees** [comment]
Bom dia! Em homologação a consulta no PDQClientExample funciona tranquilamente. Para ambiente de producao só é necessário eu alterar o login e o password? ou precisa de outra configuração? Alterei apenas o login e password, mas o resultado foi 
Exception in thread "main" com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: As credenciais informadas não são válidas. Please see the server log to find more detail regarding exact cause of the failure.

**Comment by jhoestevam** [comment]
@AllanBorgees vc tem q alterar a URI de conexão, são ambientes diferentes.

**Comment by brunocintra** [comment]
> Bom dia! Em homologação a consulta no PDQClientExample funciona tranquilamente. Para ambiente de producao só é necessário eu alterar o login e o password? ou precisa de outra configuração? Alterei apenas o login e password, mas o resultado foi
> Exception in thread "main" com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: As credenciais informadas não são válidas. Please see the server log to find more detail regarding exact cause of the failure.

@AllanBorgees você teve algum sucesso no consumo desse serviço? Poderia compartilha seu código comigo? Obrigado!

bruno.tutor@gmail.com

**Comment by avozani1500** [comment]
Bom dia senhores, alguem consegiu alguma evolução nesse barramento cns? estou com o mesmo erro do colega acima.
`Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: com.sun.xml.internal.ws.wsdl.parser.InaccessibleWSDLException: 2 counts of InaccessibleWSDLException.

java.io.IOException: Server returned HTTP response code: 403 for URL: https://servicoshm.saude.gov.br/cadsus/PDQSupplier
java.io.IOException: Server returned HTTP response code: 403 for URL: https://servicoshm.saude.gov.br/cadsus/PDQSupplier?wsdl`
